In [ ]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


In [ ]:
import  pandas as pd
m_data = pd.read_csv('/content/movies.csv')



<ipython-input-35-4f65a2c881b1>:2: DtypeWarning: Columns (0,1,4,9,13,14,19,20,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,27

In [ ]:
m_data.head()

index     budget                                    genres  \
0     0  237000000  Action Adventure Fantasy Science Fiction   
1     1  300000000                  Adventure Fantasy Action   
2     2  245000000                    Action Adventure Crime   
3     3  250000000               Action Crime Drama Thriller   
4     4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ...  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   
3  Following the death of District Attorney Harve...   112.31295  ...   
4  John Carter is a war-weary, former military ca...   43.926995  ...   

  Unnamed: 1255 Unnamed: 1256 Unnamed: 1257 Unnamed: 1258 Unnamed: 1259  \
0           NaN           NaN           NaN           NaN           NaN   
1           NaN           NaN           NaN           NaN           NaN   
2           NaN           NaN           NaN           NaN           NaN   
3           NaN           NaN           NaN           NaN           NaN   
4           NaN           NaN           NaN           NaN           NaN   

  Unnamed: 1260 Unnamed: 1261 Unnamed: 1262 Unnamed: 1263 Unnamed: 1264  
0           NaN           NaN           NaN           NaN           NaN  
1           NaN           NaN           NaN           NaN           NaN  
2           NaN           NaN           NaN           NaN           NaN  
3           NaN           NaN           NaN           NaN           NaN  
4           NaN           NaN           NaN           NaN           NaN  

[5 rows x 1265 columns]

In [ ]:
m_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4815 entries, 0 to 4814
Columns: 1265 entries, index to Unnamed: 1264
dtypes: object(1265)
memory usage: 46.5+ MB


In [ ]:
m_data.tail()

index  budget                         genres  \
4810  4798  220000          Action Crime Thriller   
4811  4799    9000                 Comedy Romance   
4812  4800       0  Comedy Drama Romance TV Movie   
4813  4801       0                            NaN   
4814  4802       0                    Documentary   

                                               homepage      id  \
4810                                                NaN    9367   
4811                                                NaN   72766   
4812  http://www.hallmarkchannel.com/signedsealeddel...  231617   
4813                        http://shanghaicalling.com/  126186   
4814                                                NaN   25975   

                                               keywords original_language  \
4810  united states\u2013mexico barrier legs arms pa...                es   
4811                                                NaN                en   
4812  date love at first sight narration investigati...                en   
4813                                                NaN                en   
4814               obsession camcorder crush dream girl                en   

                 original_title  \
4810                El Mariachi   
4811                  Newlyweds   
4812  Signed, Sealed, Delivered   
4813           Shanghai Calling   
4814          My Date with Drew   

                                               overview popularity  ...  \
4810  El Mariachi just wants to play his guitar and ...  14.269792  ...   
4811  A newlywed couple's honeymoon is upended by th...   0.642552  ...   
4812  "Signed, Sealed, Delivered" introduces a dedic...   1.444476  ...   
4813  When ambitious New York attorney Sam is sent t...   0.857008  ...   
4814  Ever since the second grade when he first saw ...   1.929883  ...   

     Unnamed: 1255 Unnamed: 1256 Unnamed: 1257 Unnamed: 1258 Unnamed: 1259  \
4810           NaN           NaN           NaN           NaN           NaN   
4811           NaN           NaN           NaN           NaN           NaN   
4812           NaN           NaN           NaN           NaN           NaN   
4813           NaN           NaN           NaN           NaN           NaN   
4814           NaN           NaN           NaN           NaN           NaN   

     Unnamed: 1260 Unnamed: 1261 Unnamed: 1262 Unnamed: 1263 Unnamed: 1264  
4810           NaN           NaN           NaN           NaN           NaN  
4811           NaN           NaN           NaN           NaN           NaN  
4812           NaN           NaN           NaN           NaN           NaN  
4813           NaN           NaN           NaN           NaN           NaN  
4814           NaN           NaN           NaN           NaN           NaN  

[5 rows x 1265 columns]

In [ ]:
m_data.shape

(4815, 1265)

In [ ]:
selected_features=['genres','keywords','tagline','cast','director','overview']

In [ ]:
print(selected_features)

['genres', 'keywords', 'tagline', 'cast', 'director', 'overview']


In [ ]:
for feature in selected_features:
  m_data[feature]=m_data[feature].fillna('')

In [ ]:
c_features=m_data['genres']+''+m_data['keywords']+''+m_data['tagline']+''+m_data['cast']+''+m_data['director']+''+m_data['overview']

In [ ]:
print(c_features)

0       Action Adventure Fantasy Science Fictioncultur...
1       Adventure Fantasy Actionocean drug abuse exoti...
2       Action Adventure Crimespy based on novel secre...
3       Action Crime Drama Thrillerdc comics crime fig...
4       Action Adventure Science Fictionbased on novel...
                              ...                        
4804    Action Crime Thrillerunited states\u2013mexico...
4805    Comedy RomanceA newlywed couple's honeymoon is...
4806    Comedy Drama Romance TV Moviedate love at firs...
4807    A New Yorker in ShanghaiDaniel Henney Eliza Co...
4808    Documentaryobsession camcorder crush dream gir...
Length: 4809, dtype: object


In [ ]:
vectorizer=TfidfVectorizer()

In [ ]:
feature_vectors=vectorizer.fit_transform(c_features)
print(feature_vectors)

  (0, 7220)	0.15785035516935053
  (0, 1439)	0.1199081573965947
  (0, 1739)	0.052225075396321666
  (0, 31513)	0.16246145304637066
  (0, 1777)	0.030339693480656647
  (0, 29063)	0.1539906205485069
  (0, 15625)	0.13752875866930966
  (0, 4080)	0.09487671257997436
  (0, 40273)	0.1400310125988128
  (0, 3695)	0.09298332420365202
  (0, 5673)	0.05877553386646216
  (0, 26688)	0.10490377402593337
  (0, 41650)	0.14686330258662852
  (0, 28933)	0.04705675230860122
  (0, 26976)	0.14599959116717343
  (0, 40143)	0.029483188972627188
  (0, 11231)	0.175752018260773
  (0, 21034)	0.03958833635652461
  (0, 25259)	0.13813004259545178
  (0, 29615)	0.19221388013997023
  (0, 6554)	0.12048046090852829
  (0, 260)	0.18691434430690138
  (0, 5886)	0.199046170127786
  (0, 33619)	0.20867574201916747
  (0, 26359)	0.11826961488654668
  :	:
  (4814, 40784)	0.08561854596281168
  (4814, 39404)	0.06944528995565871
  (4814, 28561)	0.06680549232314484
  (4814, 17918)	0.08508686819897027
  (4814, 43153)	0.08406976088295134
  (4

In [ ]:
similarity=cosine_similarity(feature_vectors)
print(similarity)

[[1.         0.04642395 0.02113123 ... 0.02552545 0.03224667 0.00674187]
 [0.04642395 1.         0.03943616 ... 0.04631069 0.03197602 0.01643634]
 [0.02113123 0.03943616 1.         ... 0.02568468 0.01203346 0.01475827]
 ...
 [0.02552545 0.04631069 0.02568468 ... 1.         0.03894633 0.02056524]
 [0.03224667 0.03197602 0.01203346 ... 0.03894633 1.         0.03418635]
 [0.00674187 0.01643634 0.01475827 ... 0.02056524 0.03418635 1.        ]]


In [ ]:
m_name=input("enter you are movie name")

enter you are movie nameAvatar


In [ ]:
list_of_titles=m_data['title'].tolist()
print(list_of_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', nan, " 'department': 'Sound'", 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON:

In [ ]:
print(type(m_name))
print(type(list_of_titles))
if isinstance(m_name, float):
    m_name = str(m_name)

if any(isinstance(title, float) for title in list_of_titles):
    list_of_titles = [str(title) for title in list_of_titles]
m_name = str(m_name) if not pd.isna(m_name) else ''
list_of_titles = [str(title) if not pd.isna(title) else '' for title in list_of_titles]


<class 'str'>
<class 'list'>


In [ ]:
find_close_match=difflib.get_close_matches(m_name, list_of_titles)
print(find_close_match)

['Avatar']


In [ ]:
close_match=find_close_match[0]
print(close_match)


Avatar


In [ ]:
index_movie=m_data[m_data.title == close_match]['index'].values[0]
print(index_movie)

0


In [ ]:
similarity_score=list(enumerate(similarity[int(index_movie)]))
print(similarity_score)

[(0, 1.0), (1, 0.04642395162163902), (2, 0.021131232240372944), (3, 0.018696666902520944), (4, 0.07400904041423993), (5, 0.03134234341513547), (6, 0.021360040509954985), (7, 0.05932205715002166), (8, 0.022211222381064773), (9, 0.026288032011542006), (10, 0.04013560565398834), (11, 0.02936675169178285), (12, 0.019608070515507364), (13, 0.02351302476830339), (14, 0.05394350039602247), (15, 0.027899525628988966), (16, 0.030081565167335532), (17, 0.02606733338286793), (18, 0.044817075833499316), (19, 0.03202863115424273), (20, 0.025561055345957807), (21, 0.01704511157797073), (22, 0.015141819173246623), (23, 0.030801847954206055), (24, 0.020584069777929703), (25, 0.024265687476167395), (26, 0.054096743691749126), (27, 0.0794651505973684), (28, 0.02081259184644514), (29, 0.0), (30, 0.0), (31, 0.04269574478948297), (32, 0.020534289240770175), (33, 0.06477572170485496), (34, 0.03849969595776534), (35, 0.024922299810423633), (36, 0.016770253174690063), (37, 0.033452716476001336), (38, 0.075387

In [ ]:
similar_movies=sorted(similarity_score,key=lambda x:x[1],reverse=True)
print(similar_movies)

[(0, 1.0), (1543, 0.1444387861274809), (3170, 0.14287831132184997), (377, 0.12676970984027078), (952, 0.11879274134797178), (96, 0.11767097298633875), (1926, 0.11627010506715782), (3616, 0.11590954782624927), (313, 0.11558652227704305), (442, 0.11411109343273716), (1287, 0.11178532066073806), (1771, 0.10738515536965726), (58, 0.10627146899788222), (539, 0.1057781842677445), (559, 0.10535029465663574), (471, 0.10343634807553335), (45, 0.10296437132863252), (1963, 0.10244480705161293), (152, 0.10200892445027795), (848, 0.09761690158427595), (1353, 0.09638913075523403), (1225, 0.09624734775500565), (1366, 0.09589542502828216), (245, 0.0930579693439423), (3742, 0.09233118974122079), (49, 0.09198736685630417), (785, 0.0910927304671814), (2415, 0.09042519390031502), (3680, 0.08994626422166636), (3117, 0.08988672474203814), (1229, 0.0893594265342941), (113, 0.08931134140285264), (644, 0.08863510006756099), (308, 0.08774936749498556), (3451, 0.08542883777984765), (1330, 0.08452563152578155), (

In [ ]:
print('Movie suggested for you:\n')
i=1
for movie in similar_movies:
  index = movie[0]
  tital_from_index=m_data[m_data.index==index]['title'].values[0]
  if(i<40):
    print(i,',',tital_from_index)
    i+=1

Movie suggested for you:

1 , Avatar
2 , Moonraker
3 , Alien
4 , Lara Croft Tomb Raider: The Cradle of Life
5 , The Book of Life
6 , Guardians of the Galaxy
7 , Lifeforce
8 , Apollo 18
9 , Treasure Planet
10 , Deep Impact
11 , Sunshine
12 , The Right Stuff
13 , Star Trek Beyond
14 , Tears of the Sun
15 , Sphere
16 , Lost in Space
17 , Terminator Salvation
18 , Space Dogs
19 , Men in Black II
20 , Alien³
21 , The Inhabited Island
22 , Aliens vs Predator: Requiem
23 , Space Chimps
24 , Gravity
25 , Cargo
26 , Star Trek Into Darkness
27 , Supernova
28 , Aliens
29 , Capricorn One
30 , Imaginary Heroes
31 , Paul
32 , Transformers
33 , The Matrix
34 , Starship Troopers
35 , The Terminator
36 , The Thing
37 , Silent Running
38 , Mission to Mars
39 , Planet of the Apes


In [ ]:
movie_name = input('Enter your movie: ')
list_of_titles = m_data['title'].astype(str).tolist()
find_close_match = difflib.get_close_matches(movie_name, list_of_titles)

if find_close_match:
    close_match = find_close_match[0]
    print(f"Closest match: {close_match}")
else:
    print("No close match found.")

movie_name=input('enter your movie:')

close_match=find_close_match[0]

index_movie=m_data[m_data.title == close_match]['index'].values[0]

similarity_score=list(enumerate(similarity[int(index_movie)]))

similar_movies=sorted(similarity_score,key=lambda x:x[1],reverse=True)

print('Movie suggested for you:\n')
i=1
for movie in similar_movies:
  index = movie[0]
  tital_from_index=m_data[m_data.index==index]['title'].values[0]
  if(i<30):
    print(i,',',tital_from_index)
    i+=1


Enter your movie: iron man
Closest match: Iron Man
enter your movie:iron man
Movie suggested for you:

1 , Up
2 , All the Pretty Horses
3 , Y Tu Mamá También
4 , An Education
5 , Hesher
6 , A Beautiful Mind
7 , Raising Helen
8 , Apocalypto
9 , Roadside Romeo
10 , Along Came Polly
11 , Boyhood
12 , I Love You Phillip Morris
13 , Aloft
14 , October Baby
15 , Michael Jordan to the Max
16 , Jersey Girl
17 , Wicker Park
18 , The New World
19 , It's a Wonderful Life
20 , Hard Candy
21 , The Emperor's Club
22 , Dancer in the Dark
23 , The Book of Mormon Movie, Volume 1: The Journey
24 , Our Brand Is Crisis
25 , Somewhere in Time
26 , Boyz n the Hood
27 , 2016: Obama's America
28 , Elizabethtown
29 , The Truman Show
